<?php
/*------------------------------------------------------------------------
# SM QuickView - Version 3.0.0
# Copyright (c) 2015 YouTech Company. All Rights Reserved.
# @license - Copyrighted Commercial Software
# Author: YouTech Company
# Websites: http://www.magentech.com
-------------------------------------------------------------------------*/
if(!(int)$this->_getConfig('isenabled', 1)) return;
?>
 
<script type="text/javascript">
	//<![CDATA[
	jQuery(document).ready(function ($) {
		function _SmQuickView(){
			var	pathbase = 'quickview/index/index',
				_item_cls = $('<?php echo $this->_getConfig('item_class'); ?>'),
				_base_url = '<?php echo str_replace("index.php/","",$this->getUrl()) ?>';
			var baseUrl = _base_url + pathbase;
			if(_item_cls.length > 0){
				_item_cls.each(function(index, el) {
					var $this = $(this)
					if($this.find("a.sm_quickview_handler").length <= 0){
						if( $this.find('a').length > 0 ){
							var _href =	($($this.find('a')[0]).attr('href').replace(_base_url,"") == '#') ? $($this.parent().find('a')[0]) : $($this.find('a')[0]);
							var	producturlpath = _href.attr('href').replace(_base_url,"");
								producturlpath = ( producturlpath.indexOf('index.php') >= 0 ) ? producturlpath.replace('index.php/','') : producturlpath;
							var	reloadurl = baseUrl+ ("/path/"+producturlpath).replace(/\/\//g,"/"),
								_quickviewbutton = "<a  class='sm_quickview_handler' title='Quick View' href='"+reloadurl+"'><?php echo $this->_getConfig('label_button'); ?></a>";
							$(el).append(_quickviewbutton);
						}
					}
				});
			}
		}
		
		$('.sm_quickview_handler').fancybox({
			<?php if (!$this->_getConfig('auto_size')){ ?>
				width : '<?php echo $this->_getConfig('popup_width').'%';?>',
				height : '<?php echo $this->_getConfig('popup_height').'%';?>',
			<?php } ?>
			autoSize       :  <?php echo $this->_getConfig('auto_size'); ?>,
			title          : 'null',
			padding		   : '0',
			scrolling      : 'auto',
			type           : 'iframe',
			openEffect     : '<?php echo $this->_getConfig('open_effect') ;?>',
			closeEffect    : '<?php echo $this->_getConfig('close_effect'); ?>',
			helpers        :{
				title:  null,
				<?php if((int)$this->_getConfig('display_overlay')) { ?>
				overlay : {
					showEarly : true
				}
				<?php } else { ?>
				overlay: null
				<?php } ?>
			},
			beforeShow : function(){
				var $this = this.element, _parent = $('.quickview-main');
				if(_parent.length > 0 ){
					var _price_box =  _parent.find('.price-box');
					if(_price_box.length > 0){
						if($('[id]',_price_box).length > 0){
							$('[id]',_price_box).each(function(i, el){
								var id_price = $(el).attr('id');
									 $(el).attr('data-idprice',id_price );
									 $(el).attr('id',id_price+'_clone');
							});
						}
					}
				}
			},
			afterShow : function(){
				if(typeof initcajax != 'undefined' && $.isFunction(initcajax)){
					initcajax();
				}

				if(typeof updateProductCompareLinks != 'undefined' && $.isFunction(updateProductCompareLinks)){
					updateProductCompareLinks();
				}else{
					$("a.link-compare").on ("click",function(e){
						e.preventDefault();
						urlcompare = $(this).attr("href");
						urlcompare = urlcompare.replace("catalog/product_compare/add","quickview/index/compare");
						window.location =  urlcompare;
						return false;
					});
				}

				if(typeof updateWishlistLinks != 'undefined' && $.isFunction(updateWishlistLinks)) {
					if(enable_ajax_wishlist){
					 updateRemoveWishLinks();
					 if(islogin=="1"){
						 updateWishlistLinks();
					 }
					 updateWishlistAddCartLinks();
					}
				}
			}
		});
		
		setInterval(function(){ _SmQuickView(); } ,1);
	});
	//]]>
</script>